### ISSUE TITLE
Provide as VSCode extension

### ISSUE THREAD

**Issue by petrroll** [surfinzap/typopo#21]
https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by petrroll** [comment]
TBH I have no experience with that :). If I find some free time I'll try to look into it, however. Can't promise anything.

**Comment by surfinzap** [comment]
No worries :) I thought you'd welcome to use Typopo in VScode, so I was assuming that you may have any specific use-case in mind.

**Comment by petrroll** [comment]
Ah apologies, I misread that. I thought you were asking for how to package
it as vscode extension. With that I have no experience.

> Note to self: don't reply to stuff immediately after waking up, brain
doesn't work.

As for use-cases, however, I had one in mind. I was thinking it would be
available as a command (similar to e.g. format code) and it would process
either the whole currently opened file (no selection) or current selection
(non-empty selection).

I'm not sure if it was desirable to actually tap into code formatting api
(not sure there's any) because that might clash with other formatters so
probably just creating custom command would be the best option.

User story:
1)
You're copying something of web and want to strip it off formatting and
then use skmwhwre else. You copy it, paste it to vscode to remove
formatting, and invoke said comment to fix it before copying again and
using somewhere else.

2)
You're writing a markdown file in Czech, you use English quotes because you
actually know where they are on the keyboard. At the end you invoke the
command to fix the whole document before committing it.

**Comment by surfinzap** [comment]
Thanks for sharing that! Understanding those use-cases is very insightful. I know, that at this point it's rather hypotethical, but would you use that only in one language (e.g. Czech) or wuuld you switch between languages often (let's on a daily basis)?

**Comment by petrroll** [comment]
I'd say more often than not. While I'd say not more than once per document but in case of the first userstory the there might be "a lot of documents" per day that might alternate between Czech and English.

**Comment by surfinzap** [comment]
Thanks for an insight! I'll wait if this issue gets a bit more traction / other suggestions and then I'll prioritize it accordingly.

**Comment by surfinzap** [comment]
Hi there, I’ve just released a very early version of extension for VS Code, that bit limited: it let’s you fix only English typos in selected text; either via menu `Typopo: Fix typos` or via `Ctrl+Alt+T` or `Cmd+Option+T`:
https://marketplace.visualstudio.com/items?itemName=brano.typopo-vscode

The configuration, more options, documentation and packaging are yet to follow. Stay tuned.

**Comment by surfinzap** [comment]
Typopo for VS Code v1.0.0 is now available at Visual Studio Marketplace → https://marketplace.visualstudio.com/items?itemName=brano.typopo-vscode
Closing this issue as solved. For further feedback and issues, please refer to [Typopo for VS Code issues](https://github.com/surfinzap/typopo-vscode/issues)
