### ISSUE TITLE
Interference between m-dash and single quote

### ISSUE THREAD

**Issue by filiph** [surfinzap/typopo#22]
Test case:
`And I ask you: "What's the idea behind this - how do you call it - 'one size fits all' approach?"`

Expected:

## And I ask you: “What’s the idea behind this—how do you call it—‘one size fits all’ approach?”

Actual:
## And I ask you: “What’s the idea behind this—how do you call it—’one size fits all’ approach?”

Note the `‘` just before "one size".

**Comment by surfinzap** [comment]
Thanks @filiph for catching and reporting that one! I'll look into fixing it with the next update.

**Comment by surfinzap** [comment]
Fixed in version [2.3.2](https://github.com/surfinzap/typopo/releases/tag/2%2F3%2F2)
