### ISSUE TITLE
End quote before period

### ISSUE THREAD

**Issue by filiph** [surfinzap/typopo#23]
Test case (from [War and Peace](https://archive.org/details/warandpeace030164mbp)):

`"But what is there to say about me?" said Pierre, his face relaxing into a careless, merry smile. "What am I? An illegitimate son!" He suddenly blushed crimson, and it was plain that he had made a great effort to say this. "Without a name and without means... And it really..." But he did not say what "it really" was. "For the present I am free and am all right. Only I haven't the least idea what I am to do; I wanted to consult you seriously."`

Expected output:

## “But what is there to say about me?” said Pierre, his face relaxing into a careless, merry smile. “What am I? An illegitimate son!” He suddenly blushed crimson, and it was plain that he had made a great effort to say this. “Without a name and without means… And it really…” But he did not say what “it really” was. “For the present I am free and am all right. Only I haven’t the least idea what I am to do; I wanted to consult you seriously.”

Actual output:

## “But what is there to say about me?” said Pierre, his face relaxing into a careless, merry smile. “What am I? An illegitimate son!” He suddenly blushed crimson, and it was plain that he had made a great effort to say this. “Without a name and without means… And it really…” But he did not say what “it really” was. “For the present I am free and am all right. Only I haven’t the least idea what I am to do; I wanted to consult you seriously”.

Note the last end quote.

Interestingly, if I convert just the last sentence, it is fine. So I'm guessing it's an interference with some other features, such as the ellipsis.

Btw, I didn't thank you yet for this package. Awesome job!

**Comment by surfinzap** [comment]
Good catch! Thanks for sharing that. I’ll look into that in one of the upcoming batches. 

I’m humbled that you like the package, stay tuned for the improvements.

**Comment by surfinzap** [comment]
Fixed in version [2.3.2](https://github.com/surfinzap/typopo/releases/tag/2%2F3%2F2)
