### ISSUE TITLE
Set up an eslint for a codebase

### ISSUE THREAD

**Issue by surfinzap** [surfinzap/typopo#32]
Set up an eslint to maintain a consistent codebase. Propose linting rules based on best practices. Lint the source and test files.

**Comment by a12baghel2** [comment]
_I want to work on this. Please assign it to me._

**Comment by surfinzap** [comment]
Hi @a12baghel2, thanks for your interest in helping out! Unfortunately, I was talking to my friend @greegus in other channel that he will take on this issue.

**Comment by a12baghel2** [comment]
okay! No problem.
