### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by surfinzap** [surfinzap/typopo#34]
Add CODE_OF_CONDUCT.md to a repo root.

Use these guidelines:
https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md

Change project email to help@typopo.org

**Comment by melarKode** [comment]
I'll do this, could you assign the task to me?

**Comment by surfinzap** [comment]
Thanks @melarKode, I’ve assigned that to you. Go ahead, take the issue and send me a PR when you’re done.

**Comment by surfinzap** [comment]
@melarKode Assuming hacktoberfest is over, I'm taking an issue over and I'll implement it.

**Comment by surfinzap** [comment]
Added to main branch.
