### ISSUE TITLE
Spanish support would be great

### ISSUE THREAD

**Issue by demian85** [surfinzap/typopo#5]
How can I help?

**Comment by surfinzap** [comment]
Hi @demian85 thanks for reaching out. Supporting Spanish meams roughly:
— identifying what Typopo corrects differently with respect to Spanish typography rules
— writing use-cases (or test-cases) for Spanish typography rules
— extending Typopo code by implementing Spanish typography rules 

What steps could you help with?

**Comment by surfinzap** [comment]
No further requirements regarding the issue, closing it.
