### ISSUE TITLE
It will add non-breaking space to image url in markdown

### ISSUE THREAD

**Issue by fabulator** [surfinzap/typopo#73]
**Describe the bug**
I'm trying to process my markdown document but url to images or documents are also processed. They should be skipped.

**To Reproduce**
1. Go to ['App typopo'](https://app.typopo.org/)
2. Switch to Czech
3. Copy:

```
![](url-to-image-5.jpg)

[fewfwe](url-to-image-5.jpg)
```

5. Result will be

```
![](url-to-image-5. jpg)
[fewfwe](url-to-image-5. jpg)
```

**Expected behavior**
Urls in markdown are not processed.

**Where it happened?
- in an app (app.typopo.org)

**Additional context**
Just want to thank you for a great tool :)

**Comment by surfinzap** [comment]
Hi @fabulator, thanks for the report! I'll look into it.

**Comment by surfinzap** [comment]
Hi @fabulator, the issue has been fixed in the [typopo app](https://app.typopo.org/) and the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=brano.typopo-vscode). Once again, thanks for the report.
